print("knock knock")
input()
print("cows go")
input()
print("No! Cows go moo! hit enter for next joke")
input()
print("How do you throw a space party?")
input()
print("you planet!!! Hit enter for questions")
input()
name = input("What is your name?")
print(f"Hello {name}")
input()
color = input("What's your favorite color?")
print(f"I like {color} too!")