name = input ("What is your name? ")
print("")
print(f"Hello {name}! *click enter*")
input()
print("Today you are going to help me create a entertaining story!")
print("")
print("I am going to ask you a few questions...")
print("")
animal = input ("Give me an animal")
print("")
print(f"I love {animal}s")
verb = input ("Give me a verb")
