name = input ("What is your name? ")
print("")
print(f"Hello {name}! *click enter*")
input()
print("Today you are going to help me create a entertaining, silly story!")
print("")
print("I am going to ask you a few questions...")
print("")
animal = input("Give me an animal: ")
print("")
print(f"I love {animal}s")
print("")
names = input("Now can you give me a name for your animal?: ")
print("")
print(f"{names} is a good one!")
print("")
adjective = input ("Give me a adjetive Ex. Fast: ")
print("")
action = input ("Give me an action. Ex. Walking: ")
print("")
print(f"I love {action}")
print("")
location = input("Can you give me a location?: ")
print("")
print(f"{location} is such a cool place!")
print("")
object = input("Can you give me a random object?: ")
print("")
pronouns = input("Can you give the animal pronouns?*Ex. She* ")
print("")
thing = input("Can you give me a random thing?: ")
print("")
food = input("Can you give me a random food?: ")
print("")
print("click enter for the story...")
input()
print("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*")
print("")
print(f"One day {names} the {animal} was {action}. {names} was trying to go to work, but the {object} was broken.")
print(f"{pronouns} decided to just walk and hope everything works out. But in {location} it was very {adjective} and {pronouns} decided to find a car and try to get to work on time.")
print(f"Thankfully, {pronouns} got to work safely because of the {thing} that teleported {food}.")
print("")
print("~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*~~~*")
print("")
print("Thank you for playing my mad libs!!!")
print("")